#!/bin/sh

echo "When given a file extension this script will rewrite every file with that extension to the one of your choosing"
echo "Which file extension should change?"
read fileExtension

# if the file extension starts with a dot, remove it
[ "${fileExtension::1}" = "." ] && fileExtension="${fileExtension#.}"

for file in *.$fileExtension; do
  echo "$file \n"
done

echo "What should the new file extension be? \n"
read newFileExtension

# if the file extension came with a dot, remove it
[ "${newFileExtension::1}" = "." ] && newFileExtension="${newFileExtension#.}"

# ${file%.{fileExtension}} -> remove the file extension
# ${}.${newFileExtension} -> add a new file extension
for file in *.${fileExtension}; do
  mv "${file}" "${file%.${fileExtension}}.${newFileExtension}"
done
