#!/bin/sh
echo 'The name of the script - $0' $0
echo 'The first argument - $1' $1
echo 'The number of arguments - $#' $#
echo 'The arguments - $@' $@
echo 'The error code of the last command - $?' $?
echo 'The process ID of the most recently executed background command $!' $!
