#!/bin/sh

# https://www.reddit.com/r/bash/comments/b2rvdy/whats_this_thing_with_getopt_vs_getopts/

while getopts "p-:" opt; do
  case "$opt" in
    p) short_circuit=" true || ";;
    -)
      case "$OPTARG" in
        help) print_help
              return 0;;
        no-delete) short_circuit=" true || ";;
        *) >&2 echo "Invalid long option ${OPTARG}.  Use --help for a help menu."
           return 2;;
      esac;;
    :) >&2 echo "Invalid Option: $OPTARG requires an argument. Use --help for a help menu."
       return 2;;
    *) >&2 echo "Invalid Option.  Use --help for a help menu."
       return 2;;
  esac
done

shift $((OPTIND-1))